modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/ThreeTAG/TriadTech/issues"
license = "All rights reserved"

[[mods]]
modId = "triadtech"
version = "${version}"
displayName = "TriadTech"
authors = "Lucraft"
description = '''
An addon for TARDIS Refined, adding new upgrade for the TARDIS!
'''
logoFile = "triadtech_banner.png"
logoBlur = false
displayURL = "https://modrinth.com/project/triadtech"
updateJSONURL = "https://squirrelcontrol.threetag.net/api/forge_updates/triadtech"

[[dependencies.triadtech]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.triadtech]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.triadtech]]
modId = "tardis_refined"
mandatory = true
versionRange = "[2.0.2,)"
ordering = "NONE"
side = "BOTH"
